# Introduction to TensorFlow 2 #

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/Users/abbeyadmin/miniforge3/envs/tf2.11/lib/python3.9/site-packages/tensorflow/_api/v2/version/__init__.py'>


First: check that running the cell above gives you tensorflow v2, from the tf2.11 environment.  Now let's declare some constants:

In [2]:
# constants
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=tf.float32)

x = np.array([[1, 2], [3, 4]])
c = tf.constant(x)

d = tensor = tf.constant(-1.0, shape=[2, 2])

**Print the contents of a,b,c and d.  Now look up the documentation for tf.rank and tf.shape and find the rank and shape of c**

**What are rank and shape telling you about the tensor?**

Now let's look at variables

In [3]:
# variables
tensorVar = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], name="tensorVar")

**Print tensorVar, and then use tensorVar.assign to make a tensor containing tensorVar+1 (i.e. [2,3...11])**

Various mathematical operations are available:

In [4]:
a        = tf.constant(3.0, dtype=tf.float32)
b        = tf.constant(4.0) # also tf.float32 implicitly
total    = a + b
product  = a * b
quotient = a/b
srt      = tf.sqrt(a) # scalar
c        = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=tf.float32) # rank 1 tensor 
d        = tf.constant([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]], dtype=tf.float32) # rank 2 tensor
aquotient= c/d    # compute a rank 2 Tensor for this division
print("a           = ", a)
print("b           = ", b)
print("Total       = ", total)
print("Product     = ", product)
print("sqrt(a)     = ", srt)
print("N=(1,...10) = ", c)
print("sqrt(c)     = ", tf.sqrt(c))
print("sqrt(d)     = ", tf.sqrt(d))

a           =  tf.Tensor(3.0, shape=(), dtype=float32)
b           =  tf.Tensor(4.0, shape=(), dtype=float32)
Total       =  tf.Tensor(7.0, shape=(), dtype=float32)
Product     =  tf.Tensor(12.0, shape=(), dtype=float32)
sqrt(a)     =  tf.Tensor(1.7320508, shape=(), dtype=float32)
N=(1,...10) =  tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float32)
sqrt(c)     =  tf.Tensor(
[1.        1.4142135 1.7320508 2.        2.236068  2.4494898 2.6457512
 2.828427  3.        3.1622777], shape=(10,), dtype=float32)
sqrt(d)     =  tf.Tensor(
[[1.       ]
 [1.4142135]
 [1.7320508]
 [2.       ]
 [2.236068 ]
 [2.4494898]
 [2.6457512]
 [2.828427 ]
 [3.       ]
 [3.1622777]], shape=(10, 1), dtype=float32)


In addition to element wise operations that are defined, TensorFlow has a number of figure of merit (metric) computations defined.  For some data (this example uses a numpy array, it also works with tensors) we can compute the sum, mean, product … of the elements

In [5]:
# generate some data and perform calculations on this
Ngen = 10
min_x = 1
max_x = 10
data = tf.random.uniform([Ngen, 1], min_x, max_x,seed=1)  # training set

data_sqrt = np.sqrt(data)

# the following are tensor outputs
print("data           = ",data)
print("sqrt(data)     = ",data_sqrt)

data           =  tf.Tensor(
[[3.1513367]
 [9.283596 ]
 [1.4546119]
 [5.4617004]
 [8.519701 ]
 [1.2382338]
 [1.7930176]
 [5.1099434]
 [7.9195533]
 [7.638727 ]], shape=(10, 1), dtype=float32)
sqrt(data)     =  [[1.7752005]
 [3.0468993]
 [1.2060729]
 [2.337028 ]
 [2.9188526]
 [1.1127596]
 [1.3390361]
 [2.2605183]
 [2.8141701]
 [2.7638247]]


**Look up the reduce functions in TensorFlow and use them to print the sum, mean, product, maximum and minimum of the data**

We can also do matrix multiplication:

In [6]:
# generate some data and perform calculations on this
I = tf.constant([[1, 0, 0],[0, 1, 0],[0, 0, 1]], name="A")
A = tf.constant([[1, 0, -1],[0, 1, 0],[-1, 0, 1]], name="A")
B = tf.constant([[1, 2, 3],[4, 5, 6],[7, 8, 9]], name="B")
C = tf.matmul(A, B)
D = tf.matmul(B, A)

print("A       = ", A)
print("B       = ", B)
print("\nC = A.B = ", C)
print("\nD = B.A = ", D)

A       =  tf.Tensor(
[[ 1  0 -1]
 [ 0  1  0]
 [-1  0  1]], shape=(3, 3), dtype=int32)
B       =  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

C = A.B =  tf.Tensor(
[[-6 -6 -6]
 [ 4  5  6]
 [ 6  6  6]], shape=(3, 3), dtype=int32)

D = B.A =  tf.Tensor(
[[-2  2  2]
 [-2  5  2]
 [-2  8  2]], shape=(3, 3), dtype=int32)


**By looking at A.I, I.A, B.I and I.B, verify that I is acting as the identity matrix**

**Use tensorflow (not numpy) to generate data for three different distributions and plot the data as histograms.  Generate 10000 data from: a normal distribution with mean=3.0, sigma=1.0, a uniform distribution between 0 and 5 and the square root of the previous uniform distribution.**

In [7]:
Ngen = 10000


In [10]:
# now plot the gaussian distribution

In [11]:
# now plot - the uniform distribution


In [12]:
# now plot - the sqrt(uniform) distribution


**CHECKPOINT - Get a demonstrator to look at your work!**

**Bonus task - can you make the same distributions with numpy and compare them?**